FROM mcr.microsoft.com/dotnet/sdk:10.0

ARG RID=linux-x64
ARG CONFIGURATION=Release

WORKDIR /src
COPY . .

RUN dotnet restore VibeVault.csproj
RUN dotnet publish VibeVault.csproj \
  -c ${CONFIGURATION} \
  -r ${RID} \
  --self-contained true \
  -p:PublishSingleFile=true \
  -p:PublishTrimmed=false \
  -o /out
